all_joints:
- - 0
- - 1
- - 2
- - 3
- - 4
- - 5
- - 6
- - 7
- - 8
- - 9
- - 10
- - 11
- - 12
- - 13
- - 14
- - 15
- - 16
- - 17
- - 18
- - 19
all_joints_names:
- Nose
- L_Eye
- R_Eye
- L_Ear
- R_Ear
- Throat
- Withers
- TailSet
- L_F_Paw
- R_F_Paw
- L_F_Wrist
- R_F_Wrist
- L_F_Elbow
- R_F_Elbow
- L_B_Paw
- R_B_Paw
- L_B_Hock
- R_B_Hock
- L_B_Stiffle
- R_B_Stiffle
alpha_r: 0.02
apply_prob: 0.5
batch_size: 1
contrast:
  clahe: true
  claheratio: 0.1
  histeq: true
  histeqratio: 0.1
convolution:
  edge: false
  emboss:
    alpha:
    - 0.0
    - 1.0
    strength:
    - 0.5
    - 1.5
  embossratio: 0.1
  sharpen: false
  sharpenratio: 0.3
cropratio: 0.4
dataset: 
  training-datasets\iteration-0\UnaugmentedDataSet_topicOct1\topic_joseph95shuffle1.mat
dataset_type: imgaug
decay_steps: 30000
display_iters: 1000
global_scale: 0.8
init_weights: 
  E:\DeepLabCut\topic-joseph-2023-10-01\dlc-models\iteration-0\topicOct1-trainset95shuffle1\train\snapshot-75000
intermediate_supervision: false
intermediate_supervision_layer: 12
location_refinement: true
locref_huber_loss: true
locref_loss_weight: 0.05
locref_stdev: 7.2801
lr_init: 0.0005
max_input_size: 1500
metadataset: 
  training-datasets\iteration-0\UnaugmentedDataSet_topicOct1\Documentation_data-topic_95shuffle1.pickle
min_input_size: 64
mirror: false
multi_stage: false
multi_step:
- - 0.005
  - 10000
- - 0.02
  - 430000
- - 0.002
  - 730000
- - 0.001
  - 1030000
net_type: resnet_50
num_joints: 20
pairwise_huber_loss: false
pairwise_predict: false
partaffinityfield_predict: false
pos_dist_thresh: 17
project_path: E:\DeepLabCut\topic-joseph-2023-10-01
rotation: 25
rotratio: 0.4
save_iters: 50000
scale_jitter_lo: 0.5
scale_jitter_up: 1.25
